Traceback (most recent call last):
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/bin/dpckan", line 8, in <module>
    sys.exit(cli())
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/dpckan/update_dataset.py", line 77, in update_cli
    update(ckan_host, ckan_key, datapackage)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/dpckan/update_dataset.py", line 37, in update
    dataset_update(ckan_instance, package)
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/venv/lib/python3.9/site-packages/dpckan/functions.py", line 146, in dataset_update
    datapackage_id = datapackage['ckan_hosts'][ckan_instance.address]['datapackage.json']
KeyError: 'ckan_hosts'
Traceback (most recent call last):
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/scripts/python/datasets_update.py", line 3, in <module>
    datasets_update()
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/scripts/python/utils.py", line 48, in datasets_update
    run_dpckan_dataset('update')
  File "/home/gabrielbdornas/code/gabrielbdornas/vagrant/etl-make/scripts/python/utils.py", line 139, in run_dpckan_dataset
    new_datapackage_ckan_hosts = Package(datapackage_path)["ckan_hosts"]
KeyError: 'ckan_hosts'
